name: Clang-Tidy

on:
  pull_request:
    paths:
      - '**/*.h'
      - '**/*.hh'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cc'
      - '**/*.cpp'
      - '**/*.cxx'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '.github/workflows/clang-tidy.yml'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang clang-tidy cmake python3-pip

      - name: Configure (RelWithDebInfo)
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEMMA_ENABLE_CLANG_TIDY=ON -DGEMMA_BUILD_ENHANCED_TESTS=OFF

      - name: Build (trigger clang-tidy)
        run: |
            cmake --build build -j $(nproc) --target gemma_all

      - name: Summarize clang-tidy command
        run: |
          grep -R "clang-tidy" build/CMakeFiles/*/build.make || true
